"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { motion } from "motion/react";
import { ArrowRight, Download, Globe, Cloud, Leaf, Briefcase, Target, FileText } from "lucide-react";
import AppShell from "@/components/AppShell";
import { Panel } from "@/components/ui/panel";
import { PageHdr } from "@/components/ui/page-header";
import { Chip } from "@/components/ui/chip";

function generateReportHTML(name: string): string {
  const now = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${name} — EcoSphere</title>
<style>body{font-family:Jost,sans-serif;color:#0e1a10;max-width:900px;margin:40px auto;padding:20px;background:#f2ede3}
h1{font-family:'Cormorant Garamond',serif;font-size:2.5rem;font-weight:300;border-bottom:2px solid #1c5c34;padding-bottom:12px;margin-bottom:24px;color:#0e1a10}
.meta{font-size:12px;color:#586358;margin-bottom:32px}
table{width:100%;border-collapse:collapse;margin:20px 0}
th,td{text-align:left;padding:10px 12px;font-size:13px;border-bottom:1px solid rgba(14,26,16,0.1)}
th{font-weight:500;color:#1c5c34;font-size:11px;text-transform:uppercase;letter-spacing:0.1em}
.section{margin:28px 0 12px;font-family:'Cormorant Garamond',serif;font-size:1.5rem;font-weight:300;color:#1c5c34}
.badge{display:inline-block;background:#1c5c34;color:#fff;padding:3px 12px;border-radius:12px;font-size:10px;letter-spacing:0.1em;text-transform:uppercase}
.footer{margin-top:48px;padding-top:16px;border-top:1px solid rgba(14,26,16,0.1);font-size:11px;color:#586358}
</style></head><body>
<h1>${name}</h1>
<div class="meta">Generated: ${now} · EcoSphere ESG Platform</div>
<div class="badge">ESG Report</div>
<p style="margin:24px 0;font-size:14px;line-height:1.7;color:#2a3a2a">
This report was automatically generated by EcoSphere AI based on your organisation's latest ESG data.
All figures are sourced from verified submissions and real-time sensor data.</p>
<h2 class="section">Executive Summary</h2>
<table><tr><th>Metric</th><th>Value</th><th>Change</th></tr>
<tr><td>ESG Total Score</td><td>87.4</td><td style="color:#1c5c34">+3.2 pts</td></tr>
<tr><td>Carbon Footprint</td><td>3,124 tCO₂e</td><td style="color:#1c5c34">−18.4%</td></tr>
<tr><td>Renewable Energy</td><td>68.2%</td><td style="color:#1c5c34">+4.1%</td></tr>
<tr><td>Compliance Rate</td><td>94.2%</td><td style="color:#1c5c34">+1.8%</td></tr>
<tr><td>Social Score</td><td>88.1</td><td style="color:#1c5c34">+2.6 pts</td></tr></table>
<h2 class="section">Environmental</h2>
<table><tr><th>Scope</th><th>tCO₂e (Q4 2024)</th><th>vs Q3</th></tr>
<tr><td>Scope 1 — Direct</td><td>940</td><td style="color:#1c5c34">−6%</td></tr>
<tr><td>Scope 2 — Energy</td><td>640</td><td style="color:#1c5c34">−4%</td></tr>
<tr><td>Scope 3 — Supply Chain</td><td>1,544</td><td style="color:#c8a96e">+2%</td></tr></table>
<h2 class="section">Social</h2>
<table><tr><th>Program</th><th>Reach</th><th>Status</th></tr>
<tr><td>DEI Initiatives</td><td>2,847 participants</td><td style="color:#1c5c34">Active</td></tr>
<tr><td>Employee Satisfaction</td><td>4.3/5.0</td><td style="color:#1c5c34">↑ 0.2</td></tr>
<tr><td>Volunteer Hours</td><td>14,820 YTD</td><td style="color:#1c5c34">+22%</td></tr></table>
<h2 class="section">Governance</h2>
<table><tr><th>Control</th><th>Score</th><th>Status</th></tr>
<tr><td>ISO 14001</td><td>94/100</td><td style="color:#1c5c34">Passed</td></tr>
<tr><td>SOC 2 Type II</td><td>97/100</td><td style="color:#1c5c34">Passed</td></tr>
<tr><td>GDPR Compliance</td><td>91/100</td><td style="color:#1c5c34">Passed</td></tr></table>
<div class="footer">EcoSphere ESG Management Platform · Confidential · Page 1 of 1</div></body></html>`;
}

function downloadReport(name: string) {
  const html = generateReportHTML(name);
  const blob = new Blob([html], { type: "text/html" });
  const a = document.createElement("a"); a.href = URL.createObjectURL(blob);
  a.download = `${name.replace(/\s+/g, "-").toLowerCase()}.html`;
  a.click(); URL.revokeObjectURL(a.href);
}

export default function ReportsPage() {
  const { data: session } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!session) router.push("/login");
  }, [session, router]);

  if (!session) return null;

  return (
    <AppShell>
      <div className="space-y-7">
        <div className="flex items-end justify-between pt-1">
          <PageHdr tag="Intelligence" title="Reports." sub="Generate, schedule and export ESG reports" />
          <motion.button onClick={() => downloadReport("ESG Report — Complete")} whileHover={{ scale: 1.02 }}
            className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground text-xs font-sans font-medium rounded-md hover:bg-primary/90 shadow-md shadow-primary/15">
            <Download className="w-3.5 h-3.5" /> Generate Report
          </motion.button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <Panel title="Templates">
            <div className="space-y-0">
              {[
                { n: "GRI Standards", d: "Global Reporting Initiative", I: Globe },
                { n: "TCFD Climate", d: "Climate-related Financial Disclosures", I: Cloud },
                { n: "CDP Carbon", d: "Carbon Disclosure Project", I: Leaf },
                { n: "ESG Investor", d: "Stakeholder ESG summary", I: Briefcase },
                { n: "UN SDG Alignment", d: "Sustainable Development Goals", I: Target },
                { n: "Annual Sustainability", d: "Full-year consolidated report", I: FileText },
              ].map(t => (
                <motion.button key={t.n} onClick={() => downloadReport(t.n)} whileHover={{ x: 4 }} transition={{ duration: 0.15 }}
                  className="w-full flex items-center justify-between py-4 border-b border-border/50 last:border-0 group text-left">
                  <div>
                    <p className="text-sm font-sans font-light text-foreground group-hover:text-primary transition-colors">{t.n}</p>
                    <p className="text-[11px] font-sans text-muted-foreground mt-0.5">{t.d}</p>
                  </div>
                  <Download className="w-3.5 h-3.5 text-muted-foreground/25 group-hover:text-primary transition-colors flex-shrink-0" />
                </motion.button>
              ))}
            </div>
          </Panel>

          <div className="space-y-4">
            <Panel title="Recent Reports">
              <div className="space-y-0">
                {[
                  { n: "Q4 2024 ESG Summary", d: "Dec 15, 2024", s: "4.2 MB" },
                  { n: "Carbon Audit Report", d: "Dec 08, 2024", s: "2.8 MB" },
                  { n: "TCFD Climate Disclosure", d: "Nov 30, 2024", s: "6.1 MB" },
                  { n: "Annual Sustainability 2024", d: "Nov 20, 2024", s: "12.4 MB" },
                ].map(r => (
                  <div key={r.n} className="flex items-center justify-between py-3.5 border-b border-border/50 last:border-0">
                    <div>
                      <p className="text-sm font-sans font-light text-foreground">{r.n}</p>
                      <p className="text-[10px] font-sans text-muted-foreground">{r.d} · {r.s}</p>
                    </div>
                    <button onClick={() => downloadReport(r.n)} className="text-muted-foreground/35 hover:text-primary transition-colors"><Download className="w-3.5 h-3.5" /></button>
                  </div>
                ))}
              </div>
            </Panel>

            <Panel title="Deadlines">
              <div className="space-y-0">
                {[
                  { n: "CDP Annual Submission", d: "Jan 31, 2025", days: 19, u: true },
                  { n: "GRI Standards Review", d: "Feb 15, 2025", days: 34, u: false },
                  { n: "Annual Report Filing", d: "Mar 01, 2025", days: 48, u: false },
                ].map(d => (
                  <div key={d.n} className="flex items-center justify-between py-3.5 border-b border-border/50 last:border-0">
                    <div>
                      <p className="text-xs font-sans font-medium text-foreground">{d.n}</p>
                      <p className="text-[10px] font-sans text-muted-foreground">{d.d}</p>
                    </div>
                    <Chip tone={d.u ? "amber" : "muted"}>{d.days}d</Chip>
                  </div>
                ))}
              </div>
            </Panel>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
